name = "insighthunter-lite"
main = "src/index.tsx"
compatibility_date = "2024-05-02"

# This binding allows the Worker to access the R2 bucket.
# The bucket itself will need to be created in your Cloudflare dashboard.
[[r2_buckets]]
binding = "CSV_BUCKET"
bucket_name = "insighthunter-lite-uploads"
